name: "get-pr-commits"
description: "A GitHub Action that get commits in current pull-request"
inputs:
  token:
    description: "A token with access to your repository scoped in as a secret"
    required: true
outputs:
  commits:
    description: "JSON stringified [{ commit { message }, sha }]"
runs:
  using: "node16"
  main: "index.js"
