name: "validate-pr-commits"
description: "A GitHub Action that validates commit messages in the current pull-request"
inputs:
  token:
    description: "A token with access to your repository scoped in as a secret"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
